---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - nginx
    - setup

- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined
  tags:
    - nginx
    - setup

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - nginx
    - install

- include: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags:
    - nginx
    - install

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - nginx
    - install

- include: setup-FreeBSD.yml
  when: ansible_os_family == 'FreeBSD'
  tags:
    - nginx
    - install

# Vhost configuration.
- include: vhosts.yml
  tags:
    - nginx
    - setup

# Nginx setup.
- name: Copy nginx configuration in place.
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx
  tags:
    - nginx
    - setup

- name: Ensure nginx is started and enabled to start at boot.
  service: name=nginx state=started enabled=yes
  tags:
    - nginx
    - setup

